spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ctf_college_registration_system
    username: root
    password: 123qweqwe
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true